name: Deploy Helm chart to AKS

on:
  push:
    branches: [master]
    
env:
  IMAGE_NAME: myimage
  ACR_NAME: myacr  
  ACR_RESOURCE_GROUP: myacrresourcegroup
  
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: 08f7b401-c4de-4d0e-b7ee-02d682ad9e3c
          tenant-id: 00709f29-2581-47e7-8b9e-1043015e06cd
          subscription-id: 8a228e0f-6360-4618-8817-357cef216c3d
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: oyohelm.azurecr.io/helmimage1:${{ github.sha }}
#           tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
#           env:
#             DOCKER_BUILDKIT: 1
#             DOCKER_BUILD_ARGS: "--platform linux/amd64,linux/arm64/v8"
#             BUILDKIT_PROGRESS: plain


      
      
