name: Deploy Helm chart to AKS

on:
  push:
    branches: [master]
    
# env:
#   IMAGE_NAME: myimage
#   ACR_NAME: myacr  
#   ACR_RESOURCE_GROUP: myacrresourcegroup
  
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure container register login
        uses: Azure/docker-login@v1
        with:
          username: oyohelm
          password: vtThtJN8NvZrjj6C0Nlv5xxXO1G6D5O6fO+4i4w/R/+ACRA0reBh
      
      - name: Azure Container Registry Build
        uses: Azure/acr-build@v1
        with:
          service_principal: myApp
          service_principal_password: 7TQ8Q~w.A9ZJSr1TFbXBVgh8OFcyP1OUbmDDwcyO
          tenant: 00709f29-2581-47e7-8b9e-1043015e06cd
          registry: oyohelm
          repository: azurerepo1
          git_access_token: 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
          
#       - name: Docker Login
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: oyohelm.azurecr.io/helmimage1:${{ github.sha }}
# #           tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
# #           env:
# #             DOCKER_BUILDKIT: 1
# #             DOCKER_BUILD_ARGS: "--platform linux/amd64,linux/arm64/v8"
# #             BUILDKIT_PROGRESS: plain
        
       



      
